/* ============================================================
 * IMPULSE VAULT — proxy/build.cjs
 * ------------------------------------------------------------
 * Generates the deployable Worker (proxy/worker.js) by:
 *   1) taking the public landing page in ../landing/,
 *   2) INLINING its style.css and app.js into one HTML document
 *      (so the Worker can serve the whole site in one response),
 *   3) injecting that HTML into worker.template.js.
 *
 * Run:  node proxy/build.cjs
 * Then deploy proxy/worker.js (wrangler deploy) OR paste its
 * contents into the Cloudflare dashboard's Worker editor.
 *
 * No dependencies — plain Node. Safe to run anytime.
 * ============================================================ */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const LANDING = path.join(ROOT, 'landing');

function read(p) {
  return fs.readFileSync(p, 'utf8');
}

// 1) Load the three landing files.
let html = read(path.join(LANDING, 'index.html'));
const css = read(path.join(LANDING, 'style.css'));
const js = read(path.join(LANDING, 'app.js'));

// 2) Inline the local stylesheet  (<link rel="stylesheet" href="style.css" />).
//    The Google Fonts <link> stays external (loads fine from any host).
const cssLink = /<link\s+rel="stylesheet"\s+href="style\.css"\s*\/?>/i;
if (!cssLink.test(html)) {
  throw new Error('build: could not find the <link href="style.css"> tag to inline.');
}
html = html.replace(cssLink, '<style>\n' + css + '\n</style>');

// 3) Inline the local script  (<script src="app.js"></script>).
const jsTag = /<script\s+src="app\.js"\s*><\/script>/i;
if (!jsTag.test(html)) {
  throw new Error('build: could not find the <script src="app.js"> tag to inline.');
}
html = html.replace(jsTag, '<script>\n' + js + '\n</script>');

// 4) Inject the combined HTML into the worker template. JSON.stringify makes a
//    bullet-proof JS string literal (handles quotes, backslashes, newlines).
const template = read(path.join(__dirname, 'worker.template.js'));
const TOKEN = "'__IV_PAGE_HTML__'";
if (template.indexOf(TOKEN) === -1) {
  throw new Error('build: worker.template.js is missing the ' + TOKEN + ' placeholder.');
}
const banner =
  '/* AUTO-GENERATED by proxy/build.cjs — do not edit by hand.\n' +
  ' * Edit ../landing/* or proxy/worker.template.js, then re-run: node proxy/build.cjs */\n';
const out = banner + template.replace(TOKEN, JSON.stringify(html));

const dest = path.join(__dirname, 'worker.js');
fs.writeFileSync(dest, out);

const kb = (Buffer.byteLength(out, 'utf8') / 1024).toFixed(1);
console.log('✓ wrote ' + path.relative(ROOT, dest) + ' (' + kb + ' KB)');
console.log('  Deploy it:  cd proxy && wrangler deploy');
console.log('  …or paste proxy/worker.js into the Cloudflare dashboard Worker editor.');
